### ISSUE TITLE
Change window title based on current url

### ISSUE THREAD

**Issue by karol-depka** [TopicFriends/TopicFriends#18]

**Comment by mjimenezmartin** [comment]
Solved in commit fa67dfde82a3b4d29aba4dde0a098dc9b9cf50d0

**Comment by karol-depka** [comment]
And for topics we need to show topic title (without %20, etc.) in window title. And there might be other cases.

**Comment by zolastro** [comment]
Solved in dd1c3c4bf5fccbc21c251d1edb6c15d9c4eba89e
