### ISSUE TITLE
Show topic icons on the map

### ISSUE THREAD

**Issue by karol-depka** [TopicFriends/TopicFriends#30]
Imagine all the Angular icons all over the map, for example :).

Good for information purposes, as well as for future TF presentations.

**Comment by karol-depka** [comment]
First simplification: only angular icon. Nice for next Angular Málaga meetup, right? :)

**Comment by zolastro** [comment]
Bigger icons = greater match score!
Little badges with their top-interests.

**Comment by zolastro** [comment]
Create a component just for the topic map

**Comment by zolastro** [comment]
Create a Json file storing the scale factor of each icon
